sudo: required
services:
  - docker

before_install:
  - docker build -t babithaloganathan/docker-react -f Dockerfile.dev .

script:
  - docker run babithaloganathan/docker-react npm run test -- --coverage